Repository KYVENetwork/chain, pull requests merged in 2023-05, with the labels that each got.

#34 chore: support heighliner
  CHANGELOG.md
  Makefile
Labels: backport/v1.0.x, backport/v1.1.x, backport/v1.2.x

#48 fix: ledger support
  CHANGELOG.md
  x/bundles/module.go
  x/bundles/types/codec.go
  x/bundles/types/message_claim_uploader_role.go
  x/bundles/types/message_skip_uploader_role.go
  x/bundles/types/message_submit_bundle_proposal.go
  x/bundles/types/message_vote_bundle_proposal.go
  x/delegation/module.go
  x/delegation/types/codec.go
  x/delegation/types/message_delegate.go
  x/delegation/types/message_redelegate.go
  x/delegation/types/message_undelegate.go
  x/delegation/types/message_withdraw_rewards.go
  x/pool/module.go
  x/pool/types/codec.go
  x/pool/types/message_defund_pool.go
  x/pool/types/message_fund_pool.go
  x/stakers/module.go
  x/stakers/types/codec.go
  x/stakers/types/message_create_staker.go
  x/stakers/types/message_join_pool.go
  x/stakers/types/message_leave_pool.go
  x/stakers/types/message_update_commission.go
  x/stakers/types/message_update_metadata.go
  x/team/module.go
  x/team/types/codec.go
  x/team/types/message_claim_account_rewards.go
  x/team/types/message_claim_authority_rewards.go
  x/team/types/message_claim_unlocked.go
  x/team/types/message_clawback.go
  x/team/types/message_create_team_vesting_account.go
Labels: backport/v1.2.x

#52 chore: prepare `v1.2` release
  .github/README.md
  CHANGELOG.md
  Makefile
Labels: backport/v1.2.x

#58 chore: include environment in release builds
  Makefile
Labels: backport/v1.1.x, backport/v1.2.x, backport/v1.3.x

#69 chore: cleanup post release
  .github/README.md
  CHANGELOG.md
  Makefile
Labels: backport/v1.3.x

#46 feat: claimable protocol commission
  CHANGELOG.md
  proto/kyve/stakers/v1beta1/events.proto
  proto/kyve/stakers/v1beta1/stakers.proto
  proto/kyve/stakers/v1beta1/tx.proto
  testutil/integration/checks.go
  x/bundles/keeper/keeper_suite_stakers_leave_test.go
  x/bundles/keeper/keeper_suite_valid_bundles_test.go
  x/bundles/keeper/keeper_suite_zero_delegation_test.go
  x/bundles/keeper/msg_server_submit_bundle_proposal.go
  x/bundles/types/expected_keepers.go
  x/stakers/client/cli/tx.go
  x/stakers/client/cli/tx_claim_commission_rewards.go
  x/stakers/keeper/getters_staker.go
  x/stakers/keeper/msg_server_claim_commission_rewards.go
  x/stakers/keeper/msg_server_claim_commission_rewards_test.go
  x/stakers/spec/03_messages.md
  x/stakers/spec/05_events.md
  x/stakers/spec/07_exported.md
  x/stakers/types/codec.go
  x/stakers/types/errors.go
  x/stakers/types/events.pb.go
  x/stakers/types/message_claim_commission_rewards.go
  x/stakers/types/stakers.pb.go
  x/stakers/types/tx.pb.go
Labels: backport/v1.3.x
